### ISSUE TITLE
Add Support for TypeScript

### ISSUE THREAD

**Issue by stephenlautier** [sindresorhus/multimatch#21]
Hi,
Are you willing to accept TypeScript typings within the repo itself?

This will make it more convenient for typescript users (and [suggested by typescript](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package)) to provide typings with the repository itself, rather than another repo (such as [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)).

Are you willing to have a pull request for this?

I will be happy to create typing for this library myself if you agree.

Thanks!

**Comment by SamVerschueren** [comment]
Sorry, it's better to publish them to DefinitelyTyped. More information can be found here  https://github.com/sindresorhus/ama/issues/439

**Comment by stephenlautier** [comment]
@SamVerschueren ahh oki thanks. Not to change your/his mind, but it would make more sense to simply allow them being done thru a PR and simply leave it to contributors to maintain if they want too

**Comment by SamVerschueren** [comment]
> Simply leave it to contributors to maintain if they want too

Exactly, you say it yourself, if they want too. If it's being shipped with the module, people want it to work. If tomorrow we do an entire overhaul of this module, and @sindresorhus doesn't want to or forgets to update the typings it will break and people start complaining because "It should work!!!". And then either Sindre has to fix it, but he won't as he doesn't care or someone from the community has to step up, has to make a PR, that has to be reviewed by someone else etc etc. The someone comes with Flow type definitions so we have to maintain both of them now. Tomorrow Google comes with Dart type definitions (not that I know of, just an example) and then we have to maintain 3 of them. So sorry, we will not change our minds anytime soon.

**Comment by stephenlautier** [comment]
I understand your concern, I will do it on Definitely Typed. Thanks anyway.

**Comment by sindresorhus** [comment]
I now accept TypeScript definitions if anyone looking is interested in submitting it here.

See: https://github.com/sindresorhus/ama/issues/439#issuecomment-414212229

Please follow this guide: https://github.com/sindresorhus/typescript-definition-style-guide
